// Re-export shared API contract types
export type {
  Conversation,
  MessageRecord,
  MessageAttachment,
  DocumentRecord,
  UserRole,
  UserProfile,
  UserProfileResponse,
  UserNotificationRecord,
  UserNotificationsResponse,
  ConversationsResponse,
  ConversationMessagesResponse,
  ReferenceDoc,
  DocVersion,
  SystemDocumentRecord,
  SystemDocumentGroup,
  AuthTokens,
  EmailCodeResponse,
  LoginData,
  LoginResponse,
  RegisterData,
  RegisterResponse,
  RefreshResponse
} from '@resuchat/shared'
